.PHONY: features model spatial anomalies all

features:
	uv run python -m pipeline.src.features

model:
	uv run python -m pipeline.src.model

spatial:
	uv run python -m pipeline.src.spatial

anomalies:
	uv run python -m pipeline.src.anomalies

all: anomalies

